# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4db8238ac91a6bb97e1ad63c20b50c059982e40f68b1a51a4838981a3dee439659137e249910bb5c77277cb961a33945bdf7d5364ec2235d9b49c27b323349b

test:
  secret_key_base: 0bfc4877bad0894f800708740c1ef18e40c66dc776f040f00206526c8fdbea2e20b3da3db05a828bf1a2ec10a1fadff0810da58ab13819712446f7f7bda02cac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
